version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=gymma_user
      - DB_PASSWORD=gymma_pass
      - DB_NAME=gymma_db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - gym-net

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: gymma_user
      POSTGRES_PASSWORD: gymma_pass
      POSTGRES_DB: gymma_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gym-net

networks:
  gym-net:

volumes:
  postgres_data:
